# Generated by Django 5.1.6 on 2025-11-12 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_search_indexes'),
        ('universities', '0002_remove_university_allow_cross_university_collaboration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status for project moderation', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when project was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['approval_status'], name='projects_pr_approva_8b8c4e_idx'),
        ),
    ]
