# Generated by Django 5.2.6 on 2026-03-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_create_admin_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor'), ('investor', 'Investor'), ('mentor', 'Mentor')], default='student', max_length=20),
        ),
    ]
