# Generated by Django 5.1.6 on 2025-11-04 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('projects', '0005_add_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_conversations', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(help_text='All participants in the group conversation', related_name='group_conversations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_conversations', to='projects.project')),
            ],
            options={
                'verbose_name': 'Group Conversation',
                'verbose_name_plural': 'Group Conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Message content', max_length=5000)),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='group_message_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='messaging.groupconversation')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_group_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Message',
                'verbose_name_plural': 'Group Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
