# Generated by Django 5.1.6 on 2025-11-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'New Follower'), ('like', 'Post Like'), ('comment', 'Post Comment'), ('project_invite', 'Project Invitation'), ('project_join', 'Project Join Request'), ('mention', 'Mention'), ('message', 'New Message'), ('announcement', 'Announcement')], max_length=20),
        ),
    ]
