# Generated by Django 5.1.6 on 2025-11-05 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_conversation_id_notification_message_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_grouped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_group_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_frequency', models.CharField(choices=[('instant', 'Instant (as they happen)'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='instant', max_length=20)),
                ('follow_enabled', models.BooleanField(default=True)),
                ('like_enabled', models.BooleanField(default=True)),
                ('comment_enabled', models.BooleanField(default=True)),
                ('mention_enabled', models.BooleanField(default=True)),
                ('message_enabled', models.BooleanField(default=True)),
                ('project_invite_enabled', models.BooleanField(default=True)),
                ('project_join_enabled', models.BooleanField(default=True)),
                ('follow_email', models.BooleanField(default=True)),
                ('like_email', models.BooleanField(default=False)),
                ('comment_email', models.BooleanField(default=True)),
                ('mention_email', models.BooleanField(default=True)),
                ('message_email', models.BooleanField(default=True)),
                ('project_invite_email', models.BooleanField(default=True)),
                ('project_join_email', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
