# Generated by Django 5.1.6 on 2025-11-12 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_group_count_notification_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='comment_email',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_frequency',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='follow_email',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='like_email',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='mention_email',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='message_email',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='project_invite_email',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='project_join_email',
        ),
    ]
