# Generated by Django 5.1.6 on 2025-11-15 07:21

from django.db import migrations


def fix_profile_urls(apps, schema_editor):
    """
    Fix any notifications that have '/profile' in their action_url
    to use '/profiles/{username}' instead
    """
    Notification = apps.get_model('notifications', 'Notification')

    # Find notifications with '/profile' (not '/profiles')
    notifications_to_fix = Notification.objects.filter(
        action_url__startswith='/profile'
    ).exclude(
        action_url__startswith='/profiles'
    )

    updated_count = 0
    for notification in notifications_to_fix:
        # If the notification has a sender, use their username
        if notification.sender:
            notification.action_url = f'/profiles/{notification.sender.username}'
            notification.save(update_fields=['action_url'])
            updated_count += 1

    if updated_count > 0:
        print(f"Fixed {updated_count} notification(s) with incorrect profile URLs")


def reverse_func(apps, schema_editor):
    # This migration is a data fix, so we don't reverse it
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notificationpreference_comment_email_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_profile_urls, reverse_func),
    ]
